import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const supabase = useSupabaseClient();
  const session = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {session ? (
          <button onClick={async () => supabase.auth.signOut()}>logout</button>
        ) : (
          <button
            onClick={async () =>
              await supabase.auth.signInWithOAuth({
                provider: "notion",
                options: {
                  redirectTo: `${process.env.NEXT_PUBLIC_URL}/auth/redirect`,
                },
              })
            }
          >
            log in
          </button>
        )}
      </main>
    </>
  );
}
